export const sampleRecords = [
  {
    country: "United States",
    region: "Americas",
    bondName: "US 10Y Treasury",
    currency: "USD",
    maturity: "10Y",
    couponRate: 4.25,
    bondPrice: 99.4,
    yieldToMaturity: 4.3,
    creditRating: "AA+",
    debtToGdp: 123,
    fiscalDeficitToGdp: 6.2,
    inflationRate: 3.1,
    policyInterestRate: 5.25,
    exchangeRateVolatility: 8.4,
    foreignExchangeReserves: 244,
    goldReserves: 8133,
    cdsSpread: 38,
    liquidityBidAskSpread: 0.03
  },
  {
    country: "Germany",
    region: "Europe",
    bondName: "Germany 10Y Bund",
    currency: "EUR",
    maturity: "10Y",
    couponRate: 2.4,
    bondPrice: 98.8,
    yieldToMaturity: 2.6,
    creditRating: "AAA",
    debtToGdp: 64,
    fiscalDeficitToGdp: 2.1,
    inflationRate: 2.4,
    policyInterestRate: 4.5,
    exchangeRateVolatility: 7.6,
    foreignExchangeReserves: 296,
    goldReserves: 3352,
    cdsSpread: 16,
    liquidityBidAskSpread: 0.04
  },
  {
    country: "Japan",
    region: "Asia",
    bondName: "Japan 10Y JGB",
    currency: "JPY",
    maturity: "10Y",
    couponRate: 0.9,
    bondPrice: 99.1,
    yieldToMaturity: 1.1,
    creditRating: "A+",
    debtToGdp: 255,
    fiscalDeficitToGdp: 5.5,
    inflationRate: 2.7,
    policyInterestRate: 0.1,
    exchangeRateVolatility: 12.2,
    foreignExchangeReserves: 1290,
    goldReserves: 846,
    cdsSpread: 32,
    liquidityBidAskSpread: 0.05
  },
  {
    country: "United Kingdom",
    region: "Europe",
    bondName: "UK 10Y Gilt",
    currency: "GBP",
    maturity: "10Y",
    couponRate: 4.2,
    bondPrice: 97.9,
    yieldToMaturity: 4.5,
    creditRating: "AA",
    debtToGdp: 101,
    fiscalDeficitToGdp: 4.4,
    inflationRate: 3.4,
    policyInterestRate: 5.25,
    exchangeRateVolatility: 9.3,
    foreignExchangeReserves: 186,
    goldReserves: 310,
    cdsSpread: 26,
    liquidityBidAskSpread: 0.06
  },
  {
    country: "Singapore",
    region: "Asia",
    bondName: "Singapore 10Y SGS",
    currency: "SGD",
    maturity: "10Y",
    couponRate: 2.8,
    bondPrice: 99.8,
    yieldToMaturity: 3.0,
    creditRating: "AAA",
    debtToGdp: 168,
    fiscalDeficitToGdp: 0.2,
    inflationRate: 2.1,
    policyInterestRate: null,
    exchangeRateVolatility: 5.1,
    foreignExchangeReserves: 352,
    goldReserves: 154,
    cdsSpread: 11,
    liquidityBidAskSpread: 0.05
  }
];

